Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"

  config.vm.provider "virtualbox" do |vb|  
     vb.gui = true
     vb.memory = "1024"
   end

   config.vm.provision "ansible" do |ansible|    
      ansible.playbook = "playbook.yml"  
   end


end
